version: 0.2
phase:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "install packages"
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "zipping package"
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post-build:
    commands:
      - aws lambda update-function-code --function-name lambda-demo --zip-file fileb://deployment_package.zip
      - echo "done!"